In [2]:
import numpy as np
import pandas as pd

In [3]:
a= ('names',1,2,3,4,5)
Se = pd.Series(a)
Se

0    names
1        1
2        2
3        3
4        4
5        5
dtype: object

In [4]:
li = list(range(10,20))
Se1 = pd.Series(li)
Se1

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [4]:
import numpy as np
import pandas as pd
data=pd.Series([1,0.5,2.5,10])
data

0     1.0
1     0.5
2     2.5
3    10.0
dtype: float64

In [5]:
data.values

array([ 1. ,  0.5,  2.5, 10. ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data.shape

(4,)

In [8]:
data.describe()

count     4.00000
mean      3.50000
std       4.41588
min       0.50000
25%       0.87500
50%       1.75000
75%       4.37500
max      10.00000
dtype: float64

In [9]:
data.ndim

1

In [13]:
data.mean()

3.5

In [15]:
data=pd.Series([1,0.5,2.5,10],
              index=['a','b','c','d'])
data

a     1.0
b     0.5
c     2.5
d    10.0
dtype: float64

In [16]:
data[0]
#when integer and string index we can use both, where as when interger is using as extended indexing 
#that will take new index value

1.0

In [17]:
data['a']

1.0

In [20]:
population={'china':500,
            'India':550,
            'USA':350,
            'UK':250,
            'PK':200}
population=pd.Series(population)
population

china    500
India    550
USA      350
UK       250
PK       200
dtype: int64

In [21]:
population.values

array([500, 550, 350, 250, 200], dtype=int64)

In [23]:
population.describe()

count      5.000000
mean     370.000000
std      152.479507
min      200.000000
25%      250.000000
50%      350.000000
75%      500.000000
max      550.000000
dtype: float64

In [24]:
pd.Series(5,index=[10,20,30])

10    5
20    5
30    5
dtype: int64

In [26]:
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

3    c
2    a
dtype: object

In [27]:
area={'china':500,
            'India':550,
            'USA':350,
            'UK':250,
            'PK':200}
area=pd.Series(area)
area

china    500
India    550
USA      350
UK       250
PK       200
dtype: int64

In [30]:
country=pd.DataFrame({'population':population,
                     'area':area})
country

population  area
china         500   500
India         550   550
USA           350   350
UK            250   250
PK            200   200

In [31]:
country.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, china to PK
Data columns (total 2 columns):
population    5 non-null int64
area          5 non-null int64
dtypes: int64(2)
memory usage: 280.0+ bytes


In [33]:
country.describe()

population        area
count    5.000000    5.000000
mean   370.000000  370.000000
std    152.479507  152.479507
min    200.000000  200.000000
25%    250.000000  250.000000
50%    350.000000  350.000000
75%    500.000000  500.000000
max    550.000000  550.000000

In [35]:
country.values

array([[500, 500],
       [550, 550],
       [350, 350],
       [250, 250],
       [200, 200]], dtype=int64)

In [38]:
country.index

Index(['china', 'India', 'USA', 'UK', 'PK'], dtype='object')

In [39]:
country.ndim

2

In [41]:
country.shape

(5, 2)

In [51]:
country.keys

<bound method NDFrame.keys of        population  area
china         500   500
India         550   550
USA           350   350
UK            250   250
PK            200   200>

In [46]:
country.columns

Index(['population', 'area'], dtype='object')

In [54]:
data=np.arange(12,24).reshape(4,3)
df=pd.DataFrame(data)
df

0   1   2
0  12  13  14
1  15  16  17
2  18  19  20
3  21  22  23

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
0    4 non-null int32
1    4 non-null int32
2    4 non-null int32
dtypes: int32(3)
memory usage: 176.0 bytes


In [57]:
df.describe()

0          1          2
count   4.000000   4.000000   4.000000
mean   16.500000  17.500000  18.500000
std     3.872983   3.872983   3.872983
min    12.000000  13.000000  14.000000
25%    14.250000  15.250000  16.250000
50%    16.500000  17.500000  18.500000
75%    18.750000  19.750000  20.750000
max    21.000000  22.000000  23.000000

In [63]:
a=np.random.random(25).reshape(5,5)
dm=pd.DataFrame(a,columns=[1,2,3,4,5],index=[1,2,3,4,5])
dm

1         2         3         4         5
1  0.520124  0.216521  0.741633  0.943677  0.844994
2  0.401998  0.011290  0.092333  0.198194  0.633025
3  0.697824  0.733797  0.885255  0.219078  0.815876
4  0.125857  0.505566  0.892240  0.681603  0.461088
5  0.909768  0.152225  0.041234  0.645580  0.997755

In [1]:
data=[{'a':i,'b':2*i,'c':2**i+2}
     for i in range(1,4)]
pd.DataFrame(data)


NameError: name 'pd' is not defined

In [ ]:
import numpy as np
import pandas as pd
ind=pd.Index([2,6,5,7])
ind

In [3]:
a=5
a

5

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
data = pd.read_csv("Data")
data

FileNotFoundError: [Errno 2] File b'births.csv' does not exist: b'births.csv'